(function () {
  "use strict";

  // Brand data + the English dictionary. The Spanish copy lives in index.html
  // (content first, JS only enriches); every key below maps a data-i18n /
  // data-i18n-html / data-i18n-attr hook in the markup to its English text.
  window.__BRAND__ = {
    name: "Miguel Ángel Rosingana",
    role: "Data Analyst",
    email: "miguel.rosin@gmail.com",
    links: {
      linkedin: "https://www.linkedin.com/in/miguel-angel-rosingana",
      github: "https://github.com/MiguelAngelRosingana"
    },

    i18n: {
      en: {
        "meta.title": "Miguel Ángel Rosingana — Data Analyst · Power BI, DAX, SQL",
        "meta.desc": "Data Analyst in Madrid. I turn scattered data into models that hold up: Power BI, DAX, SQL and Python. Microsoft PL-300 certified.",

        "ui.skip": "Skip to content",
        "ui.menu": "Menu",
        "ui.theme": "Toggle light / dark theme",
        "ui.lang": "Language",
        "ui.langes": "Español",
        "ui.langen": "English",
        "ui.enlarge": "Enlarge screenshot",
        "ui.repo": "View repository",
        "ui.close": "Close",
        "ui.prev": "Previous screenshot",
        "ui.next": "Next screenshot",
        "ui.viewer": "Screenshot viewer",
        "ui.mainnav": "Main navigation",

        "nav.origin": "Story",
        "nav.method": "Method",
        "nav.path": "Career",
        "nav.projects": "Projects",
        "nav.stack": "Stack",
        "nav.contact": "Contact",

        "hero.tag": "I turn scattered data into <em>models that hold up</em>.",
        "hero.lead": "A clean star schema, DAX measures that tell the truth, and a report that answers the question on the first screen.",
        "hero.cta1": "Write to me",
        "hero.cta2": "Download CV",
        "hero.photoalt": "Portrait of Miguel Ángel Rosingana",
        "hero.credlabel": "Microsoft credential",

        "band.aria": "Key facts",
        "band.1.v": "Since 2024",
        "band.2.v": "Power BI, DAX, SQL and Python",
        "band.2.l": "Focus",
        "band.3.l": "Certified in 2026",
        "band.4.v": "Madrid or remote",
        "band.4.l": "Location",

        "origin.label": "Story",
        "origin.h": "What interested me wasn’t the screen, but <em>what was behind it.</em>",
        "origin.p1": "I came to data from web development. I studied a Higher Diploma in Web Application Development —Java, PHP, databases— and that is where I realised that what interested me most wasn’t the screen, but what was behind it: where the data came from and what could be read in it.",
        "origin.p2": "I have worked as a Data Analyst since 2024. At a BPO I handled client data in Excel and Power BI and, above all, learned to automate: what used to be hours of formulas and copy-paste ended up as macros, Power Query and dataflows. Today, in advertising, I work on national and international projects: I extract with SQL, PostgreSQL and BigQuery, model the data, and build the reports people decide with.",
        "origin.quote": "A well-designed model answers questions nobody had asked yet.",
        "origin.p3": "Outside work I keep building models for the fun of it: Spain's electricity grid and the FC Barcelona season.",

        "method.label": "Method",
        "method.h": "How I <em>work</em>",
        "method.sub": "Three ideas that hold everything else up.",
        "m1.k": "Data modelling",
        "m1.h": "The model comes first.",
        "m1.p": "I decide the granularity and separate facts from dimensions before I open Power BI. A well-planned model means a new question gets answered by adding a measure, not by rebuilding the spreadsheet.",
        "m2.k": "Automation",
        "m2.h": "Make it repeat itself.",
        "m2.p": "I turn hours of formulas and copy-paste into repeatable processes: macros, Power Query and dataflows that run the same way every time.",
        "m3.k": "Communication",
        "m3.h": "The answer, on the first screen.",
        "m3.p": "Reports that answer the question straight away. The detail is one click away; what matters is in plain sight.",

        "path.label": "Career",
        "path.h": "Four years <em>towards data</em>",
        "path.sub": "Most recent first.",
        "kind.exp": "Experience",
        "kind.edu": "Education",
        "kind.cert": "Certification",
        "t1.range": "July",
        "t1.p": "Microsoft’s official certification on preparing, modelling, visualising and deploying data with Power BI.",
        "t2.range": "→ present",
        "t2.org": "PRIME IT · Advertising",
        "t2.p": "National and international advertising projects. Extraction, transformation and modelling with Power BI, Google BigQuery, SQL and PostgreSQL to measure campaign and operations performance.",
        "t3.title": "Master’s in Data Analytics",
        "t3.p": "SQL, Python (pandas, NumPy, Matplotlib), Power BI and advanced Excel; report automation and Big Data techniques.",
        "t4.p": "Client data analysis with Excel and Power BI. Process automation with advanced formulas, macros, Power Query and dataflows, plus interactive dashboards for decision-making.",
        "t5.title": "Specialisation in AI and Big Data",
        "t5.org": "Alfonso X el Sabio University",
        "t5.p": "Machine Learning, NLP and Big Data with Python, R and Scala; Hadoop, Spark and Kafka; AWS services.",
        "t6.title": "Higher Diploma in Web Application Development",
        "t6.org": "Alfonso X el Sabio University",
        "t6.p": "Full-stack development with Java, PHP, HTML, CSS and JavaScript, and database management. Final project: EcoChef.",

        "proj.label": "Projects",
        "proj.h": "Three projects, <em>three design decisions</em>",
        "proj.sub": "Every case is told the same way: what the problem was, how I approached it and what came out of it.",
        "pfa.problem": "Problem",
        "pfa.approach": "Approach",
        "pfa.result": "Result",

        "p1.title": "Spain's electricity data pipeline",
        "p1.note": "Real data · public API",
        "p1.f1": "days of data loaded",
        "p1.f2": "quality checks",
        "p1.f3": "automated tests",
        "p1.problem": "Spain's electricity generation and demand data is public, but it comes through an API with quirks: range limits, an ambiguous 400 error, series that appear and disappear, and revisions to days already published. Loading it with a naive script gives figures nobody can reconcile.",
        "p1.approach": "A layered ELT pipeline —raw response, staging and a star schema— with watermark-based incremental loading and an overlap window that picks up the source's revisions. Eleven SQL quality checks run in the same transaction: if one with error severity fails, nothing is left half-loaded in the model. The tests use real API responses and a real PostgreSQL database.",
        "p1.result": "Three and a half years of generation by technology and demand for the five electricity systems, loaded in about four minutes. A daily run takes about eight seconds and, if the source has not changed, modifies nothing. On top of it, a three-page Power BI report whose figures match the SQL views: renewable share, technology mix and a comparison between systems.",
        "p1.alt1": "Power BI report, summary page: generation, demand and renewable share, and the monthly renewable share against the same month of the previous year.",
        "p1.cap1": "Summary · renewable share and generation by family",
        "p1.alt2": "Power BI report, generation mix: stacked columns by month and a matrix with each technology's weight by year.",
        "p1.cap2": "Mix and evolution · weight of each technology",

        "p2.title": "FC Barcelona, 2026/27 season",
        "p2.note": "Ongoing",
        "p2.f1": "row per event",
        "p2.f2": "competitions",
        "p2.f3": "report pages",
        "p2.problem": "Following a whole season —LaLiga, Champions League, Copa del Rey and Supercopa— without stopping at the scoreline: who scores, who plays, and at what minute the cards come.",
        "p2.approach": "The decision that carries the project is the grain: the fact table stores one row per goal, assist and card, with its minute, instead of one row per match. I ruled out APIs and scraping on purpose: a manual Excel template doesn’t depend on keys that expire or on sites that change structure.",
        "p2.result": "A four-page report —summary, scorers, minutes and discipline— that answers questions nobody planned for (minutes per player, goals by fifteen-minute period, when the cards arrive) by adding a measure, without rebuilding the model. It keeps growing as the season goes on.",
        "p2.alt1": "Power BI report, FC Barcelona season summary: KPIs and match-by-match detail.",
        "p2.cap1": "Summary · KPIs and match-by-match detail",
        "p2.alt2": "Power BI report, scorers page: goal involvements and split by period of the match.",
        "p2.cap2": "Scorers · involvements and match periods",

        "p3.title": "EcoChef",
        "p3.note": "Final degree project",
        "p3.f1": "views",
        "p3.f2": "external API",
        "p3.f3": "fallback mode",
        "p3.f3v": "Offline",
        "p3.problem": "Food gets thrown away for a silly reason: you don’t know what you have or what can be cooked with it before it expires. Recipe books work the other way round: you pick the recipe, then go shopping.",
        "p3.approach": "A Flask web app that starts from the fridge inventory (SQLite) and asks the Spoonacular API for the recipes that use the most available ingredients. Since the API only understands English, I built a two-way translation layer; and a local fallback keeps the app running when the API doesn’t respond.",
        "p3.result": "The app suggests what to cook with what is already there, flags what is missing, builds the shopping list and shows the stock in a chart panel. It is the final project of my Higher Diploma in Web Application Development.",
        "p3.alt1": "EcoChef home page with shortcuts to fridge, recipes and shopping list, and the stock summary.",
        "p3.cap1": "Home · stock summary",
        "p3.alt2": "EcoChef recipe finder results: recipes ranked by how many fridge ingredients they use, and what is missing.",
        "p3.cap2": "Recipes · suggestions and what’s missing",

        "cta.h": "Got data that doesn’t tell <em>the story it should?</em>",
        "cta.link": "Tell me about it",

        "stack.label": "Stack",
        "stack.h": "What I <em>work with</em>",
        "s1.p": "From the model to the published report.",
        "s1.i1": "Data modelling",
        "s1.i5": "RLS (row-level security)",
        "s2.h": "Data",
        "s2.p": "Extract, query and transform.",
        "s2.i4": "Python (pandas)",
        "s3.h": "Automation",
        "s3.p": "Let the repetitive work run itself.",
        "s3.i1": "Advanced Excel",
        "s3.i4": "Data cleaning",
        "stack.langs": "Native Spanish · English B1–B2",

        "contact.label": "Contact",
        "contact.h": "Shall we talk? <em>Tell me the problem.</em>",
        "contact.sub": "I work from Madrid or remotely. Reach me by email or LinkedIn.",
        "c1.l": "Email",
        "c4.l": "CV",
        "c4.v": "Download PDF",
        "mail.subject": "Contact from your portfolio",

        "foot.role": "Data Analyst · Madrid",
        "foot.top": "Back to top",
        "foot.made": "HTML, CSS and JavaScript. No frameworks."
      }
    }
  };
})();
